// <auto-generated />
namespace Fitness.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class n3n3sdlskdlksldk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(n3n3sdlskdlksldk));
        
        string IMigrationMetadata.Id
        {
            get { return "202009061934118_n3n3sdlskdlksldk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
