// <auto-generated />
namespace Fitness.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Nagham080920202 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nagham080920202));
        
        string IMigrationMetadata.Id
        {
            get { return "202009081002493_Nagham080920202"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
