// <auto-generated />
namespace Fitness.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Permission090920NS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Permission090920NS));
        
        string IMigrationMetadata.Id
        {
            get { return "202009091245315_Permission090920NS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
