// <auto-generated />
namespace Fitness.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addClass060920nagham : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addClass060920nagham));
        
        string IMigrationMetadata.Id
        {
            get { return "202009061534558_addClass060920-nagham"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
