// <auto-generated />
namespace Fitness.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addClass060920 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addClass060920));
        
        string IMigrationMetadata.Id
        {
            get { return "202009060957209_addClass060920"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
